version: '3'
services:
    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:4.0.1
        ports:
            - "40101:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/conf1:/data/db
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always
        
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:4.0.1
        ports:
            - "40102:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/conf2:/data/db
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:4.0.1
        ports:
            - "40103:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/conf3:/data/db
        restart: always 