version: '3'
services:
    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:4.0.1
        ports:
            - "40011:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/data11:/data/db
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always
        
    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo:4.0.1
        ports:
            - "40012:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/data12:/data/db
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo:4.0.1
        ports:
            - "40013:27017"
        command: mongod --keyFile /scripts/mongo-keyfile --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/data13:/data/db
        restart: always   
