version: '3'
services:
    mongo-router:
        container_name: "mongo-router"
        image: mongo:4.0.1
        ports:
            - "30097:27017"
        external_links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        command: mongos --keyFile /scripts/mongo-keyfile --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017 --bind_ip 0.0.0.0
        volumes:
          - ./scripts:/scripts
          - /docker/mongo/router:/data/db
        restart: always
